<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
            <a href="/">
                <img src="/img/twitter_logo.png" />
            </a>

        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome Completo">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
                  <?php if (isset($this->view->erroEmailExistente) && $this->view->erroEmailExistente): ?>
                      <div class="alert alert-danger">O E-mail inserido já está em uso. Por favor, tente outro</div>
                  <?php endif; ?>
              </div>

                <div class="form-group">
                    <input type="date" value="<?= $this->view->usuario['data_nasc'] ?>" name="data_nasc" class="form-control">
                </div>

                <div class="form-group">
                    <input type="text" value="<?= $this->view->usuario['localizacao'] ?>" name="localizacao" class="form-control" placeholder="Cidade, País">
                </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha">
              </div>

                <div class="form-group">
                    <input type="text" value="" name="nome_usuario" class="form-control" placeholder="Nome Usuário ">
                    <?php if (isset($this->view->erroNomeUsuarioExistente) && $this->view->erroNomeUsuarioExistente): ?>
                        <small class="form-text text-danger">O nome do usuário já está em uso. Por favor, escolha outro.</small>
                    <?php endif; ?>
                </div>
              
              <div class="mt-4 mb-4">
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

                <?php if ($this->view->erroCadastro) { ?>
                    <small class="form-text text-danger">Erro ao tentar realizar o cadastro, verifique se os campos
                    foram preenchidos corretamente!</small>
                <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  