<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">

		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">

					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" name="pesquisaPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
            
            <?php foreach ($this->view->usuarios as $indice_arr => $usuario) { ?>
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
                                    <?= $usuario['nome'] ?>
								</div>

								<div class="col-md-6 d-flex justify-content-end">
									<div>
                                        <?php
                                        if ($usuario['seguir_sn'] == 0) { // Se não estiver seguindo, exibe apenas o botão "Seguir"
                                            ?>
                                            <a href="/acao?acao=seguir&id_usuario=<?=$usuario['id'] ?>" class="btn btn-success seguir-btn">Seguir</a>
                                        <?php } ?>

                                        <?php
                                        if ($usuario['seguir_sn'] == 1) { // Se estiver seguindo, exibe apenas o botão "Deixar de Seguir"
                                            ?>
                                            <a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id'] ?>" class="btn btn-danger deixar-seguir-btn">Deixar de seguir</a>
                                        <?php } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
            <?php } ?>
        </div>
	</div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function() {
        // Lidar com o clique no botão "Seguir"
        $(document).on('click', '.seguir-btn', function(e) {
            e.preventDefault(); // Impedir o comportamento padrão do link

            var url = $(this).attr('href');

            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    // Atualizar apenas o botão atual
                    $(e.target).replaceWith('<a href="' + url.replace('seguir', 'deixar_de_seguir') + '" class="btn btn-danger deixar-seguir-btn">Deixar de seguir</a>');
                }
            });
        });

        // Lidar com o clique no botão "Deixar de Seguir"
        $(document).on('click', '.deixar-seguir-btn', function(e) {
            e.preventDefault(); // Impedir o comportamento padrão do link

            var url = $(this).attr('href');

            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    // Atualizar apenas o botão atual
                    $(e.target).replaceWith('<a href="' + url.replace('deixar_de_seguir', 'seguir') + '" class="btn btn-success seguir-btn">Seguir</a>');
                }
            });
        });
    });
</script>
